
USE ass;
CREATE TABLE TheDD(
	maDinhDanh VARCHAR(10) PRIMARY KEY,
	trangThai NVARCHAR(15)
);
CREATE TABLE doanhThu(
maDT VARCHAR(10) PRIMARY KEY,
tongDiem money,
donDaTao int,
ghiChu NVARCHAR(50)
);
CREATE TABLE LoaiDoUong(
maLDU VARCHAR(10) PRIMARY KEY,
ten NVARCHAR(10)
);
CREATE TABLE DoUong(
maDU VARCHAR(10) PRIMARY KEY,
tenDU NVARCHAR(15),
anhDoUong image,
size VARCHAR(5),
maLDU VARCHAR(10) FOREIGN KEY REFERENCES LoaiDoUong(maLDU)
);
CREATE TABLE ChiTietPhieuBan(
ID int IDENTITY(1,1) PRIMARY KEY,
maDU VARCHAR(10) FOREIGN KEY REFERENCES DoUong(maDU),
gia money
);
CREATE TABLE PhieuBanHang(
maPhieu VARCHAR(10) PRIMARY KEY,

CREATE TABLE NhanVien(
maSN NVARCHAR(10) PRIMARY KEY,
hoVaTen NVARCHAR(30),
Namsinh DATE,
anh image,
maDT VARCHAR(10) FOREIGN KEY REFERENCES LoaiDoUong(maLDU),


